document.addEventListener("DOMContentLoaded", () => {
    updateDate();
    updateDailyContent();
});

// 1. FUNCIÓN PARA FECHA ELEGANTE
function updateDate() {
    const dateElement = document.getElementById('current-date');
    const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
    const today = new Date();
    // Capitalizar primera letra (ej: Lunes)
    let dateString = today.toLocaleDateString('es-ES', options);
    dateString = dateString.charAt(0).toUpperCase() + dateString.slice(1);
    dateElement.textContent = dateString;
}

// 2. BASES DE DATOS (Contenido Profesional)
const facts = [
    { text: "El 'olor a lluvia' tiene nombre científico: Petricor, y es causado por bacterias del suelo.", category: "Ciencia" },
    { text: "Si pudieras doblar una hoja de papel 42 veces, su grosor llegaría hasta la Luna.", category: "Matemáticas" },
    { text: "Las vacas tienen mejores amigas y se estresan si las separan.", category: "Naturaleza" },
    { text: "La Universidad de Oxford es más antigua que el Imperio Azteca.", category: "Historia" },
    { text: "Los humanos compartimos el 50% de nuestro ADN con los plátanos.", category: "Genética" },
    { text: "Japón tiene una palabra, 'Tsundoku', para comprar libros y no leerlos.", category: "Cultura" },
    { text: "Un día en Venus es más largo que un año en Venus.", category: "Espacio" },
    { text: "Las abejas pueden reconocer rostros humanos individuales.", category: "Naturaleza" },
    { text: "Nintendo fue fundada cuando todavía existía el Imperio Otomano (1889).", category: "Historia" },
    { text: "Las nubes cumulus promedio pesan alrededor de 500.000 kilos (como 100 elefantes).", category: "Clima" },
    { text: "Es imposible tararear mientras te aprietas la nariz (inténtalo).", category: "Cuerpo Humano" },
    { text: "Los tiburones existieron antes que los árboles.", category: "Evolución" },
    { text: "El animal nacional de Escocia es el Unicornio.", category: "Cultura" },
    { text: "La miel es el único alimento que nunca se estropea; se ha encontrado miel comestible en tumbas egipcias.", category: "Ciencia" },
    { text: "Tu nariz y tus orejas nunca dejan de crecer.", category: "Biología" },
    { text: "En promedio, pasas 6 meses de tu vida esperando en semáforos en rojo.", category: "Sociedad" },
    { text: "Los koalas tienen huellas dactilares casi idénticas a las humanas.", category: "Animales" },
    { text: "Cleopatra vivió más cerca de la invención del iPhone que de la construcción de las Pirámides.", category: "Historia" },
    { text: "Llover diamantes es posible en Neptuno y Urano.", category: "Espacio" },
    { text: "Los pulpos tienen tres corazones y nueve cerebros.", category: "Biología" },
    { text: "El 'hashtag' (#) se llama en realidad 'octothorpe'.", category: "Lenguaje" },
    { text: "Los plátanos son bayas, pero las fresas no.", category: "Botánica" },
    { text: "La Torre Eiffel puede crecer 15 cm en verano debido a la expansión térmica.", category: "Física" },
    { text: "Hay más estrellas en el universo que granos de arena en todas las playas de la Tierra.", category: "Espacio" },
    { text: "Las nutrias se dan la mano mientras duermen para no separarse flotando.", category: "Animales" },
    { text: "El corazón de una ballena azul es tan grande que un humano podría nadar por sus arterias.", category: "Naturaleza" },
    { text: "En Mercurio, el día solar es más largo que su año: tarda ~59 días terrestres en girar sobre sí mismo, pero solo 88 días en orbitar el Sol.", category: "Espacio" },
    { text: "Saturno es el único planeta del Sistema Solar con densidad media menor que la del agua: en teoría podría flotar en una bañera gigante.", category: "Espacio" },
    { text: "La luz del Sol tarda ~80 minutos en llegar desde el Sol hasta Saturno.", category: "Espacio" },
    { text: "Los anillos principales de Saturno suelen tener un grosor vertical de apenas ~10 metros, aunque se extienden cientos de miles de kilómetros a lo ancho.", category: "Espacio" },
    { text: "En el polo norte de Saturno hay una corriente en chorro con forma de hexágono de ~30.000 km de ancho.", category: "Espacio" },
    { text: "Un día en Saturno dura ~10,7 horas.", category: "Espacio" },
    { text: "Un año en Neptuno dura ~165 años terrestres.", category: "Espacio" },
    { text: "Un día en Júpiter dura cerca de 10 horas.", category: "Espacio" },
    { text: "Venus gira al revés (rotación retrógrada): allí, el Sol “sale” por el oeste y “se pone” por el este.", category: "Espacio" },
    { text: "La Estación Espacial Internacional (EEI) orbita a una altitud promedio de ~250 millas (≈400 km).", category: "Espacio" },
    { text: "La EEI viaja a ~17.500 millas por hora (mph).", category: "Espacio" },
    { text: "La EEI da una vuelta completa a la Tierra aproximadamente cada 90 minutos.", category: "Espacio" },
    { text: "En 24 horas, la EEI completa ~16 órbitas y ve ~16 amaneceres y atardeceres.", category: "Espacio" },
    { text: "La EEI ha estado ocupada de forma continua desde noviembre de 2000.", category: "Espacio" },
    { text: "Para compensar la pérdida de masa ósea y muscular en microgravedad, los astronautas entrenan al menos 2 horas al día en la EEI.", category: "Espacio" },
    { text: "Desde la EEI se han tomado más de 3,5 millones de fotografías de la Tierra.", category: "Espacio" },
    { text: "A pesar del mito, la Gran Muralla China no es visible desde la Luna y suele ser muy difícil (o imposible) distinguirla desde la órbita a simple vista.", category: "Espacio" },
    { text: "La Luna se aleja de la Tierra a razón de ~3,8 cm por año.", category: "Espacio" },
    { text: "Aproximadamente el 71% de la superficie de la Tierra está cubierta por agua.", category: "Planeta Tierra" },
    { text: "Los océanos contienen ~96,5% de toda el agua del planeta.", category: "Planeta Tierra" },
    { text: "Si toda el agua de la Tierra formara una sola esfera, mediría ~860 millas (≈1.385 km) de diámetro.", category: "Planeta Tierra" },
    { text: "Si solo tomas el agua dulce líquida (subterránea + lagos/ríos/pantanos), esa esfera sería de ~169,5 millas (≈272,8 km) de diámetro.", category: "Planeta Tierra" },
    { text: "Si tomas únicamente el agua dulce de lagos y ríos, la esfera sería de apenas ~34,9 millas (≈56,2 km) de diámetro.", category: "Planeta Tierra" },
    { text: "La profundidad promedio del océano es de ~3.682 metros.", category: "Océanos" },
    { text: "El punto más profundo conocido (Challenger Deep) tiene ~10.935 metros de profundidad.", category: "Océanos" },
    { text: "Se estima que aproximadamente la mitad de la producción de oxígeno del planeta proviene del océano.", category: "Océanos" },
    { text: "Una sola bacteria fotosintética oceánica, Prochlorococcus, puede producir hasta ~20% del oxígeno de la biosfera.", category: "Océanos" },
    { text: "Aunque el océano produce al menos ~50% del oxígeno, una cantidad similar también se consume por respiración y descomposición en el mar.", category: "Océanos" },  
    { text: "De toda el agua dulce del planeta, más de ~68% está “atrapada” en hielo y glaciares.", category: "Planeta Tierra" },
    { text: "Aproximadamente ~30% del agua dulce está bajo tierra (agua subterránea).", category: "Planeta Tierra" },
    { text: "En volumen, los ríos representan alrededor de 1/10.000 de una milésima parte del 1% del agua total de la Tierra.", category: "Planeta Tierra" },
    { text: "Las placas tectónicas se mueven unos pocos centímetros al año: un ritmo parecido al crecimiento de las uñas.", category: "Geología" },
    { text: "El Mauna Kea (Hawái), medido desde su base en el fondo del mar hasta la cima, es más alto que el Everest medido desde el nivel del mar.", category: "Geología" },
    { text: "El mayor terremoto registrado fue el de Chile de 1960, con magnitud 9,5.", category: "Geología" },
    { text: "Para terremotos grandes, los sismólogos suelen usar magnitud de momento (Mw); la escala de Richter se considera en gran medida obsoleta para esos casos.", category: "Geología" },
    { text: "Un rayo puede calentar el aire de su canal hasta ~50.000°F (unas 5 veces más caliente que la superficie del Sol).", category: "Clima" },
    { text: "Regla “flash-to-bang”: si cuentas los segundos entre el relámpago y el trueno, y los divides por 5, obtienes aproximadamente la distancia en millas.", category: "Clima" },
    { text: "Los rayos pueden caer lejos de la lluvia (hasta ~25 millas); una recomendación común es esperar 30 minutos tras el último trueno antes de reanudar actividades.", category: "Clima" },
    { text: "Mammoth Cave es el sistema de cuevas más largo conocido del mundo.", category: "Geografía" },
    { text: "La velocidad de la luz en el vacío está definida exactamente como 299.792.458 m/s en el SI.", category: "Metrología" },
    { text: "Desde el 20 de mayo de 2019, las unidades del SI se definen a partir de constantes físicas con valores fijos.", category: "Metrología" },
    { text: "El número de Avogadro tiene un valor fijo en el SI: 6,02214076 × 10^23 mol⁻¹.", category: "Metrología" },
    { text: "La constante de Planck tiene un valor fijo en el SI: 6,62607015 × 10⁻34 J·s.", category: "Metrología" },
    { text: "La constante de Boltzmann tiene un valor fijo en el SI: 1,380649 × 10⁻23 J/K.", category: "Metrología" },
    { text: "El segundo del SI se define fijando la frecuencia del cesio-133: ΔνCs = 9 192 631 770 Hz.", category: "Metrología" },
    { text: "En el punto triple del agua, la temperatura es 0,01°C y su presión de vapor característica es ~611,657 Pa.", category: "Física" },
    { text: "Si estiras todo el ADN de una célula humana, mide aproximadamente 2 metros de largo.", category: "Biología" },
    { text: "Comprimir esos ~2 metros de ADN dentro de un núcleo de ~6 μm de diámetro es como meter ~40 km de hilo finísimo dentro de una pelota de tenis.", category: "Biología" },
    { text: "Tus papilas gustativas se regeneran aproximadamente cada 10 días.", category: "Cuerpo Humano" },
    { text: "El hígado puede volver a un tamaño normal incluso después de que se haya extirpado hasta ~90% del órgano.", category: "Cuerpo Humano" },
    { text: "La córnea (la “ventana” transparente del ojo) no tiene vasos sanguíneos; recibe nutrientes por difusión desde lágrimas y humor acuoso.", category: "Cuerpo Humano" },
    { text: "Los tardígrados han sobrevivido exposición al vacío y radiación del espacio en experimentos de la Agencia Espacial Europea (ESA).", category: "Animales" },
    { text: "El camarón mantis puede golpear tan rápido que genera burbujas de cavitación que emiten luz y calor intenso.", category: "Animales" },
    { text: "La rana de bosque (wood frog) puede sobrevivir congelándose en invierno gracias a compuestos que protegen sus células.", category: "Animales" },
    { text: "Los wombats son famosos por producir heces con forma de cubo.", category: "Animales" },
    { text: "Mamuts lanudos sobrevivieron en la isla de Wrangel hasta hace ~4.000 años.", category: "Evolución" },
    { text: "La Antártida es el desierto más grande de la Tierra (por su bajísima precipitación).", category: "Naturaleza" },
    { text: "El océano está lleno de plancton fotosintético: aunque es microscópico, produce enormes cantidades de oxígeno.", category: "Naturaleza" },
    { text: "Yellowstone se estableció el 1 de marzo de 1872 y suele citarse como el primer parque nacional del mundo.", category: "Historia" },
    { text: "Yellowstone alberga aproximadamente la mitad de los géiseres activos del planeta.", category: "Naturaleza" },
    { text: "Francia utilizó la guillotina como método legal de ejecución hasta 1977.", category: "Historia" },
    { text: "La palabra “robot” se popularizó por la obra R.U.R. (1920) del escritor checo Karel Čapek.", category: "Lenguaje" },
    { text: "El primer sitio web se conserva en info.cern.ch (CERN), considerado la “casa” del primer website.", category: "Tecnología" },
    { text: "El 30 de abril de 1993, CERN puso el software de la World Wide Web en el dominio público, impulsando su expansión.", category: "Tecnología" },
    { text: "El sistema de QR Code fue desarrollado por ingenieros de DENSO WAVE y se presentó en 1994.", category: "Tecnología" },
    { text: "Las siglas “QR” significan “Quick Response” (respuesta rápida).", category: "Tecnología" },
    { text: "DENSO liberó el QR Code bajo una patente abierta (open patent), lo que facilitó su adopción.", category: "Tecnología" },
    { text: "Adobe Acrobat y el formato PDF se lanzaron formalmente el 15 de junio de 1993.", category: "Tecnología" },
    { text: "Wi-Fi no es un acrónimo: es un nombre de marca creado con fines de marketing.", category: "Tecnología" },
    { text: "“Ojalá” proviene de la expresión árabe “in shaa Allah” (“si Dios quiere”).", category: "Lenguaje" },
    { text: "El puntito sobre la “i” y la “j” se llama “tittle”.", category: "Lenguaje" },
    { text: "“Quarantine” viene del italiano relacionado con “cuarenta días”, por antiguos periodos de aislamiento.", category: "Lenguaje" },
    { text: "Canadá tiene la línea costera más larga del mundo (del orden de ~243.000 km).", category: "Geografía" },
    { text: "El primer set de “emoji” modernos se atribuye a Shigetaka Kurita en 1999 (un conjunto temprano tenía 176 iconos).", category: "Cultura" },
    { text: "Si la Tierra fuera del tamaño de una moneda de cinco centavos (nickel), Saturno sería aproximadamente del tamaño de un balón de voleibol.", category: "Espacio" },
    { text: "Los paneles solares de la EEI tienen una envergadura de ~109 m, más que la de un Airbus A380 (~80 m).", category: "Tecnología" },
    { text: "El espacio habitable y de trabajo de la EEI se describe como más grande que una casa de seis habitaciones.", category: "Espacio" },
    { text: "El sistema principal de anillos de Saturno se extiende hasta ~282.000 km desde el planeta.", category: "Espacio" },
    { text: "Un año en Mercurio (una vuelta al Sol) dura 88 días terrestres.", category: "Espacio" },    
];

const questions = [
    "¿Qué habilidad te gustaría dominar instantáneamente?",
    "¿Cuál es el libro o película que cambió tu forma de pensar?",
    "Si el dinero no importara, ¿a qué te dedicarías?",
    "¿Qué consejo le darías a tu 'yo' de hace 5 años?",
    "¿Cuál es tu lugar favorito en el mundo (en el que hayas estado)?",
    "Define el éxito en una sola frase.",
    "¿Cuál es el recuerdo de tu infancia que te hace sonreír siempre?",
    "Si pudieras tener una cena con cualquier personaje histórico, ¿a quién elegirías?",
    "¿Qué canción te recuerda inmediatamente a mí?",
    "Si el dinero no fuera un problema, ¿a dónde viajaríamos mañana mismo?",
    "¿Cuál consideras que es tu mayor talento inútil?",
    "¿Qué es lo que más valoras de nuestra relación?",
    "Si pudieras ver una estadística de tu vida, ¿cuál te gustaría ver?",
    "¿Qué película podrías ver 10 veces seguidas sin aburrirte?",
    "¿Cuál fue el mejor consejo que te han dado y quién te lo dio?",
    "Si escribieras un libro sobre tu vida, ¿cómo se llamaría el capítulo actual?",
    "¿Qué pequeño detalle te alegra el día instantáneamente?",
    "Si fueras un animal, ¿cuál serías y por qué?",
    "¿Qué superpoder elegirías: volar o ser invisible?",
    "Describe tu día perfecto de principio a fin.",
    "¿Qué es lo que más te gusta de ti mismo/a?",
    "Si pudieras aprender un idioma instantáneamente, ¿cuál sería?",
    "¿Cuál es tu miedo más irracional?",
    "¿Qué harías si hubiera un apocalipsis zombie ahora mismo?",
    "¿Cuál es tu forma favorita de recibir cariño?",
    "Si pudieras cambiar algo del mundo con un chasquido, ¿qué sería?",
    "¿Qué parte de tu rutina te gustaría rediseñar desde cero?",
    "¿Qué hábito te ha dado mejores resultados con el menor esfuerzo?",
    "¿Qué cosa te gustaría dejar de postergar y por qué crees que la postergas?",
    "¿Qué te gustaría que la gente entendiera de ti sin tener que explicarlo?",
    "¿Qué valor te guía incluso cuando nadie te está mirando?",
    "¿Qué decisión pequeña terminó cambiando mucho tu camino?",
    "¿Qué creencia tenías hace años y hoy te da risa haber defendido?",
    "¿Qué tema podrías hablar durante horas sin aburrirte?",
    "¿Qué te entusiasma aprender este año, aunque sea por curiosidad?",
    "¿Qué parte de tu personalidad has aprendido a apreciar con el tiempo?",
    "¿Qué te cuesta pedir: ayuda, perdón o cariño?",
    "¿Qué te hace sentir realmente en calma?",
    "¿Qué situación te hace sentir más valiente de lo que pensabas?",
    "¿Qué “regla” social te parece absurda y te gustaría romper?",
    "¿Qué te gustaría celebrar más seguido en tu vida cotidiana?",
    "¿Qué cosa te gustaría que existiera pero todavía no se ha inventado?",
    "¿Qué cosa que te daba miedo antes hoy haces con naturalidad?",
    "¿Qué te hace sentir orgulloso/a pero casi nunca lo dices en voz alta?",
    "¿Qué emoción te cuesta más manejar y cómo la sueles lidiar?",
    "¿Qué momento reciente te hizo decir: “ok, estoy creciendo”?",
    "¿Qué parte de tu historia te ha hecho más fuerte, aunque no lo elegiste?",
    "¿Qué es lo más importante que has aprendido sobre la amistad?",
    "¿Qué te gustaría cambiar de tu forma de comunicarte?",
    "¿Qué malentendido sobre ti te gustaría corregir para siempre?",
    "¿Qué cosa te da energía y cuál te la drena sin que lo notes?",
    "¿Qué te gustaría que fuera diferente en tus mañanas?",
    "¿Qué te gustaría que fuera diferente en tus noches?",
    "¿Qué te ayuda a recuperar el foco cuando te dispersas?",
    "¿Qué te cuesta soltar: control, expectativas o orgullo?",
    "¿Qué te gustaría que te preguntaran más seguido?",
    "¿Qué tema te da curiosidad pero te intimida por “difícil”?",
    "¿Qué recuerdo te gustaría revivir solo por 10 minutos?",
    "¿Qué cosa te parecía “de gente grande” y ahora entiendes perfecto?",
    "¿Qué parte de tu infancia te gustaría conservar para siempre?",
    "¿Qué cosa aprendiste a la mala, pero agradeces haber aprendido?",
    "¿Qué fracaso terminó siendo un favor disfrazado?",
    "¿Qué es algo que hoy sabes que antes no estabas listo/a para entender?",
    "¿Qué conversación te cambió la forma de ver a alguien?",
    "¿Qué persona te enseñó una lección sin intentarlo?",
    "¿Qué te gustaría mejorar: paciencia, disciplina o confianza?",
    "¿Qué te gustaría hacer más: crear, explorar o conectar?",
    "¿Qué significa para ti “estar bien” en un día normal?",
    "¿Qué te hace sentir “en casa” aunque estés lejos de tu casa?",
    "¿Qué tradición te gustaría empezar (contigo o con alguien más)?",
    "¿Qué tradición te gustaría rescatar de tu familia o tu cultura?",
    "¿Qué cosa te gustaría que hiciéramos más seguido juntos/as?",
    "¿Qué cosa te gustaría que cuidáramos mejor en nuestra relación?",
    "¿Qué te hace sentir realmente acompañado/a?",
    "¿Qué gesto pequeño para ti significa muchísimo?",
    "¿Qué límites te hacen bien, aunque a veces incomoden?",
    "¿Qué te gustaría que hiciéramos cuando uno de los dos esté estresado?",
    "¿Qué señal tuya debería aprender a leer mejor la gente que te quiere?",
    "¿Qué te ayuda a sentirte seguro/a en una relación?",
    "¿Qué es lo que más te cuesta expresar cuando algo te duele?",
    "¿Qué te gustaría que hagamos distinto cuando discutimos?",
    "¿Qué conflicto crees que vale la pena tener (por algo importante)?",
    "¿Qué detalle te hace sentir elegido/a?",
    "¿Qué te hace sentir respetado/a de verdad?",
    "¿Qué te gustaría que yo supiera de tu forma de amar?",
    "¿Qué te gustaría que construyamos a largo plazo (sin hablar de dinero)?",
    "¿Qué promesa te gustaría hacernos sin que sea cursi?",
    "¿Qué conversación difícil crees que nos haría bien tener pronto?",
    "¿Qué te gustaría que fuera “sagrado” en nuestra semana (un ritual)?",
    "¿Qué te gustaría que no se pierda nunca entre nosotros/as?",
    "¿Qué cosa te hace sentir que somos un equipo?",
    "¿Qué te gustaría que celebremos de nosotros, incluso en días comunes?",
    "¿Qué te gustaría que yo entienda mejor de tu mundo interno?",
    "¿Qué te gustaría pedir sin sentirte vulnerable?",
    "¿Qué te gustaría recibir más: tiempo, atención o tranquilidad?",
    "¿Qué lugar te gustaría volver a visitar pero con otros ojos?",
    "¿Qué tipo de viaje te recarga más: aventura, descanso o cultura?",
    "¿Qué ciudad o paisaje te gustaría conocer por su “vibra” más que por turismo?",
    "¿Qué comida probarías sí o sí si estuvieras en un país nuevo?",
    "¿Qué experiencia te gustaría tener al menos una vez en la vida?",
    "¿Qué cosa te gustaría hacer “antes de…” (sin dramatismo, solo intención)?",
    "¿Qué sueño te da vergüenza decir porque lo sientes demasiado grande?",
    "¿Qué proyecto personal te gustaría empezar si tuvieras 3 horas extra a la semana?",
    "¿Qué habilidad social te gustaría pulir (escuchar, negociar, decir que no)?",
    "¿Qué te gustaría que fuera tu “sello” como persona?",
    "¿Qué te gustaría que dijeran de ti en una despedida (sin solemnidad)?",
    "¿Qué te gustaría agradecerte a ti mismo/a hoy?",
    "¿Qué te gustaría perdonarte para vivir más liviano/a?",
    "¿Qué te gustaría dejar de justificar y simplemente hacer?",
    "¿Qué parte de tu vida te gustaría simplificar?",
    "¿Qué es algo que te tomas demasiado en serio?",
    "¿Qué es algo que te gustaría tomarte más en serio?",
    "¿Qué te gustaría cambiar de tu relación con el teléfono y las pantallas?",
    "¿Qué te gustaría que fuera diferente en tus redes sociales (o tu consumo de contenido)?",
    "¿Qué te da nostalgia y por qué crees que te pega tanto?",
    "¿Qué te da esperanza últimamente?",
    "¿Qué te hace sentir “vivo/a” de inmediato?",
    "¿Qué te cuesta más: empezar, mantener o terminar?",
    "¿Qué te gustaría practicar más: gratitud, presencia o curiosidad?",
    "¿Qué te gustaría explorar: espiritualidad, creatividad o deporte?",
    "¿Qué cosa te gustaría aprender a disfrutar sin culpa?",
    "¿Qué te gustaría hacer aunque seas malo/a al principio?",
    "¿Qué te gustaría que fuera tu “plan B” si todo se reiniciara mañana?",
    "¿Qué persona (real o ficticia) te inspira por su forma de enfrentar la vida?",
    "¿Qué frase te gustaría que aparezca en una camiseta que te describa hoy?",
    "¿Qué sería un “lujo” para ti que no cuesta dinero?",
    "¿Qué momento del día sientes más tuyo?",
    "¿Qué parte de tu personalidad sale solo cuando hay mucha confianza?",
    "¿Qué mentira piadosa te dices a ti mismo/a y te gustaría dejar de creer?",
    "¿Qué te gustaría que tu versión del futuro te agradezca?",
    "¿Qué te gustaría que tu versión del pasado sepa sobre tu presente?",
    "¿Qué cosa te gustaría que hagamos hoy para que mañana sea más fácil?",
    "¿Qué señal te indica que necesitas descansar de verdad?",
    "¿Qué te gustaría que sea diferente en tu vida dentro de 12 meses, con algo concreto?",
    "¿Qué pregunta te gustaría que te responda la vida (si pudiera hablar)?",
    "¿Qué te gustaría descubrir de ti que todavía no has explorado?",
    "¿Qué te gustaría que el mundo aprendiera más rápido como sociedad?",
    "¿Qué cosa pequeña podríamos hacer para mejorar el día de alguien hoy?",
    "¿Qué cosa te gustaría coleccionar si tuvieras espacio infinito?",
    "¿Qué “mini-aventura” podríamos inventarnos este fin de semana?",
    "¿Qué te gustaría que sea nuestro plan cuando todo salga mal: humor, silencio o abrazo?",
    "¿Qué tipo de apoyo te funciona más: soluciones, escucha o compañía?",
    "¿Qué te gustaría que yo haga cuando te note apagado/a?",
    "¿Qué te gustaría que yo deje de asumir sobre ti?",
    "¿Qué cosa no estás dispuesto/a a negociar en tu paz mental?",
    "¿Qué cosa te gustaría recordar siempre de esta etapa de tu vida?",
    "¿Qué te gustaría decirte a ti mismo/a cuando vuelvas a dudar?",
    "¿Qué te gustaría celebrar hoy, aunque sea algo mínimo?"
];

const quotes = [
    { text: "La vida es lo que pasa mientras estás ocupado haciendo otros planes.", author: "John Lennon" },
    { text: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali" },
    { text: "La simplicidad es la máxima sofisticación.", author: "Leonardo da Vinci" },
    { text: "Todo parece imposible hasta que se hace.", author: "Nelson Mandela" },
    { text: "Sé el cambio que quieres ver en el mundo.", author: "Mahatma Gandhi" },
    { text: "El amor no consiste en mirarse el uno al otro, sino en mirar juntos en la misma dirección.", author: "Antoine de Saint-Exupéry" },
    { text: "No tenemos poco tiempo, sino que perdemos mucho.", author: "Séneca" },
    { text: "La felicidad depende de nosotros mismos.", author: "Aristóteles" },
    { text: "Lo que no te mata, te hace más fuerte.", author: "Friedrich Nietzsche" },
    { text: "El único modo de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
    { text: "Donde hay amor hay vida.", author: "Mahatma Gandhi" },
    { text: "La medida del amor es amar sin medida.", author: "San Agustín" },
    { text: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali" },
    { text: "La simplicidad es la máxima sofisticación.", author: "Leonardo da Vinci" },
    { text: "El futuro pertenece a quienes creen en la belleza de sus sueños.", author: "Eleanor Roosevelt" },
    { text: "Sé el cambio que quieres ver en el mundo.", author: "Mahatma Gandhi" },
    { text: "Amar es encontrar en la felicidad de otro tu propia felicidad.", author: "Gottfried Leibniz" },
    { text: "La vida es 10% lo que te ocurre y 90% cómo reaccionas a ello.", author: "Charles R. Swindoll" },
    { text: "Cree que puedes y ya estarás a medio camino.", author: "Theodore Roosevelt" },
    { text: "El amor es la única fuerza capaz de transformar un enemigo en amigo.", author: "Martin Luther King Jr." },
    { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau" },
    { text: "La mejor manera de predecir el futuro es creándolo.", author: "Peter Drucker" },
    { text: "A veces, el corazón ve lo que es invisible para el ojo.", author: "H. Jackson Brown Jr." },
    { text: "Eres el dueño de tu destino. Eres el capitán de tu alma.", author: "William Ernest Henley" },
    { text: "Todo lo que puedes imaginar es real.", author: "Pablo Picasso" },

    { text: "Simplifica, simplifica. (\"Simplify, simplify.\")", author: "Henry David Thoreau" },
    { text: "He dicho lo que pienso, y ahora puedo ir a cualquier parte. (\"I have spoken my mind, and can go anywhere now.\")", author: "Charlotte Brontë" },
    { text: "No soy un pájaro; ninguna red me atrapa; soy un ser humano libre con voluntad propia. (\"I am no bird; and no net ensnares me; I am a free human being with an independent will...\")", author: "Charlotte Brontë" },
    { text: "Cuidado: soy temible y, por eso, poderoso. (\"Beware, for I am fearless and therefore powerful.\")", author: "Mary Shelley" },
    { text: "La venganza permanece: la venganza, desde ahora más querida que la luz o el alimento. (\"revenge remains—revenge, henceforth dearer than light or food!\")", author: "Mary Shelley" },
    { text: "Fue el mejor de los tiempos; fue el peor de los tiempos… (\"It was the best of times, it was the worst of times…\")", author: "Charles Dickens" },
    { text: "Deberías desear ser amado y temido; pero, si has de prescindir de uno, es más seguro ser temido. (\"one should wish to be both... it is much safer to be feared than loved\")", author: "Niccolò Machiavelli" },
    { text: "Es mucho más seguro ser temido que amado, cuando no puedes ser ambas cosas. (\"it is much safer to be feared than loved\")", author: "Niccolò Machiavelli" },
    { text: "Perder a un padre puede considerarse una desgracia; perder a ambos parece descuido. (\"To lose one parent... to lose both looks like carelessness.\")", author: "Oscar Wilde" },
    { text: "La única forma de librarse de una tentación es ceder a ella. (\"The only way to get rid of a temptation is to yield to it.\")", author: "Oscar Wilde" },
    { text: "Resístela, y tu alma enferma de anhelo por lo que se prohibió. (\"Resist it, and your soul grows sick with longing...\")", author: "Oscar Wilde" },
    { text: "Se ha dicho que los grandes acontecimientos del mundo suceden en el cerebro. (\"It has been said that the great events of the world take place in the brain.\")", author: "Oscar Wilde" },
    { text: "Escúchalos: los hijos de la noche. ¡Qué música hacen! (\"Listen to them—the children of the night. What music they make!\")", author: "Bram Stoker" },
    { text: "En la ciudad no pueden entender los sentimientos del cazador. (\"you dwellers in the city cannot enter into the feelings of the hunter\")", author: "Bram Stoker" },
    { text: "El trabajo es lo que uno está obligado a hacer; el juego es lo que no está obligado a hacer. (\"Work consists of whatever a body is obliged to do... Play... not obliged to do.\")", author: "Mark Twain" },
    { text: "Para que alguien desee algo, basta con hacerlo difícil de conseguir. (\"to make a man or a boy covet a thing... make the thing difficult to attain\")", author: "Mark Twain" },
    { text: "No sirve volver a ayer, porque entonces yo era una persona distinta. (\"it's no use going back to yesterday, because I was a different person then.\")", author: "Lewis Carroll" },
    { text: "Las explicaciones toman un tiempo terrible. (\"explanations take such a dreadful time.\")", author: "Lewis Carroll" },
    { text: "Cuando has eliminado lo imposible, lo que quede —por improbable que sea— debe ser la verdad. (\"when you have eliminated the impossible... must be the truth\")", author: "Arthur Conan Doyle" },
    { text: "¿No es bonito pensar que mañana es un día nuevo sin errores todavía? (\"tomorrow is a new day with no mistakes in it yet\")", author: "L. M. Montgomery" },
    { text: "Nunca cometo el mismo error dos veces. (\"I never make the same mistake twice.\")", author: "L. M. Montgomery" },
    { text: "No hay nada bueno o malo; el pensamiento lo hace así. (\"there is nothing either good or bad but thinking makes it so\")", author: "William Shakespeare" },
    { text: "La brevedad es el alma del ingenio. (\"brevity is the soul of wit\")", author: "William Shakespeare" },
    { text: "¡Oh Dios! Podría estar encerrado en una cáscara de nuez y sentirme rey de un espacio infinito… (\"I could be bounded in a nutshell... king of infinite space\")", author: "William Shakespeare" },
    { text: "Los hombres, a veces, son dueños de su destino. (\"Men at some time are masters of their fates\")", author: "William Shakespeare" },
    { text: "La culpa, querido Bruto, no está en nuestras estrellas, sino en nosotros mismos. (\"The fault, dear Brutus, is not in our stars, / But in ourselves\")", author: "William Shakespeare" },
    { text: "Somos de la materia de la que están hechos los sueños… (\"We are such stuff as dreams are made on\")", author: "William Shakespeare" },
    { text: "El mundo entero es un escenario, y todos —hombres y mujeres— son actores. (\"All the world's a stage, / And all the men and women merely players\")", author: "William Shakespeare" },
    { text: "Algunos nacen grandes, otros alcanzan la grandeza, y a otros la grandeza les cae encima. (\"Some are born great, some achieve greatness...\")", author: "William Shakespeare" },
    { text: "—Con la iglesia hemos dado, Sancho.", author: "Miguel de Cervantes" },
    { text: "La libertad, Sancho, es uno de los más preciosos dones que a los hombres dieron los cielos…", author: "Miguel de Cervantes" },
    { text: "Por la libertad, así como por la honra, se puede y debe aventurar la vida.", author: "Miguel de Cervantes" },
    { text: "Caminante, no hay camino: se hace camino al andar.", author: "Antonio Machado" },
    { text: "Al andar se hace camino, y al volver la vista atrás se ve la senda que nunca se ha de volver a pisar.", author: "Antonio Machado" },
    { text: "¿Qué es la vida? — Un frenesí.", author: "Pedro Calderón de la Barca" },
    { text: "Que toda la vida es sueño, y los sueños sueño son.", author: "Pedro Calderón de la Barca" },
    { text: "¿Qué es poesía? ¿Y tú me lo preguntas? Poesía... eres tú.", author: "Gustavo Adolfo Bécquer" },
    { text: "Poderoso caballero es don Dinero.", author: "Francisco de Quevedo" },
    { text: "Madre, yo al oro me humillo; él es mi amante y mi amado.", author: "Francisco de Quevedo" },
    { text: "Y pues quien le trae al lado es hermoso, aunque sea fiero.", author: "Francisco de Quevedo" },
    { text: "Nada te turbe; nada te espante; todo se pasa.", author: "Santa Teresa de Jesús" },
    { text: "La paciencia todo lo alcanza.", author: "Santa Teresa de Jesús" },
    { text: "Quien a Dios tiene, nada le falta. Solo Dios basta.", author: "Santa Teresa de Jesús" },
    { text: "Hay grandeza en esta visión de la vida… (\"There is grandeur in this view of life...\")", author: "Charles Darwin" },
    { text: "De un comienzo tan simple, formas infinitas —las más bellas y maravillosas— han sido y están siendo evolucionadas. (\"from so simple a beginning endless forms...\")", author: "Charles Darwin" },
    { text: "Es una verdad universalmente reconocida… (\"It is a truth universally acknowledged...\")", author: "Jane Austen" },
    { text: "Declaro que, después de todo, no hay placer como leer… (\"I declare, after all, there is no enjoyment like reading!\")", author: "Jane Austen" },
    { text: "¿Me atrevo? ¿Me atrevo? (\"Do I dare?\" and, \"Do I dare?\")", author: "T. S. Eliot" },
    { text: "¿Me atrevo a perturbar el universo? (\"Do I dare / Disturb the universe?\")", author: "T. S. Eliot" },
    { text: "Los hombres no se perturban por las cosas, sino por las opiniones que tienen de las cosas. (\"Men are disturbed not by things, but by the views...\")", author: "Epicteto" },
    { text: "No exijas que las cosas sucedan como deseas; desea que sucedan como suceden, y todo irá bien. (\"Require not things to happen as you wish...\")", author: "Epicteto" },
];

// 3. SELECCIÓN DIARIA SINCRONIZADA
function getDayOfYear() {
    const now = new Date();
    const start = new Date(now.getFullYear(), 0, 0);
    const diff = now - start;
    const oneDay = 1000 * 60 * 60 * 24;
    return Math.floor(diff / oneDay);
}

function updateDailyContent() {
    const dayIndex = getDayOfYear();

    // Índices cíclicos
    const factIndex = dayIndex % facts.length;
    const questionIndex = dayIndex % questions.length;
    const quoteIndex = dayIndex % quotes.length;

    // Actualizar DOM - Curiosidad
    const factObj = facts[factIndex];
    document.getElementById("daily-fact").textContent = factObj.text;
    document.getElementById("fact-category").textContent = factObj.category;

    // Actualizar DOM - Pregunta
    document.getElementById("daily-question").textContent = questions[questionIndex];

    // Actualizar DOM - Cita
    const quoteObj = quotes[quoteIndex];
    document.getElementById("daily-quote").textContent = `"${quoteObj.text}"`;
    document.getElementById("quote-author").textContent = quoteObj.author;
}
